# 暂未实现
# version: "3.3"
# services:
#   database:
#     image: liuyh73/moneydodo_db:latest
#     container_name: moneydodo_db
#     restart: always
#     ports: 
#       - "3306:3306"
#     # volumes: 
#     #   - data:/mysql
#     # environment:
#     #   MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
#     #   MYSQL_DATABASE: starwars
#     #   MYSQL_USER: starwars
#     #   MYSQL_PASSWORD_FILE: /run/secrets/db_user_password
#     # secrets:
#     #   - db_root_password
#     #   - db_user_password
#   server:
#     depends_on:
#       - database
#     image: liuyh73/moneydodo_main:latest
#     container_name: moneydodo_main
#     restart: always
#     ports: 
#       - "8998:8998"
#     external_links:
#       - moneydodo_db:moneydodo_db
#   client:
#     depends_on:
#       - database
#       - server
#     image: liuyh73/moneydodo_web:latest
#     container_name: moneydodo_web
#     restart: always
#     ports:
#       - "80:80"
#     external_links:
#       - moneydodo_main:moneydodo_main
# # secrets:
# #   db_user_password:
# #     file: conf/db_user_password.txt
# #   db_root_password:
# #     file: conf/db_root_password.txt

# # volumes:
# #   data:
